import type { IntakeSection } from "@/types";

export const INTAKE_SECTIONS: IntakeSection[] = [
  {
    id: 1,
    key: "stats",
    title: "Stats",
    fullTitle: "Personal Stats",
    icon: "BarChart3",
    color: "#3b82f6",
    questions: [
      { id: "age", label: "Age", type: "text", placeholder: "e.g. 24" },
      { id: "sex", label: "Biological Sex", type: "radio", options: ["Male", "Female"] },
      { id: "height", label: "Height", type: "text", placeholder: "e.g. 183 cm or 6'0\"" },
      { id: "weight", label: "Current Weight", type: "text", placeholder: "e.g. 80 kg or 176 lbs" },
      {
        id: "goalWeight",
        label: "Goal Weight or Goal Look / Feel",
        type: "textarea",
        placeholder: "e.g. 72 kg, or 'I want to see my abs and feel lighter'",
      },
      {
        id: "pace",
        label: "How quickly do you want to reach your goal?",
        type: "radio",
        options: [
          "Steady & sustainable (lifestyle change)",
          "Moderate pace (some structure)",
          "As fast as safely possible",
        ],
      },
    ],
  },
  {
    id: 2,
    key: "lifestyle",
    title: "Lifestyle",
    fullTitle: "Daily Lifestyle",
    icon: "Activity",
    color: "#10b981",
    questions: [
      {
        id: "jobType",
        label: "What best describes your job?",
        type: "radio",
        options: [
          "Desk job / mostly sitting",
          "On my feet most of the day",
          "Manual / physical labour",
          "Mixed (desk + some movement)",
        ],
      },
      {
        id: "exerciseFreq",
        label: "How many times per week do you exercise?",
        type: "radio",
        options: ["0 — not yet", "1–2 days", "3–4 days", "5–6 days", "Every day"],
      },
      {
        id: "exerciseType",
        label: "What type of exercise do you do?",
        type: "checkbox",
        options: [
          "Weight training",
          "Running / cardio",
          "Sports / team games",
          "Yoga / Pilates",
          "Cycling / swimming",
          "Walking",
          "Other",
        ],
      },
      {
        id: "exerciseOther",
        label: "If 'Other', describe briefly",
        type: "text",
        placeholder: "e.g. martial arts, CrossFit...",
        optional: true,
      },
      {
        id: "sleep",
        label: "How many hours of sleep per night?",
        type: "radio",
        options: ["Less than 5 hrs", "5–6 hrs", "6–7 hrs", "7–8 hrs", "8+ hrs"],
      },
      {
        id: "stress",
        label: "Current stress levels",
        type: "radio",
        options: ["Low", "Moderate", "High", "Very high"],
      },
      {
        id: "alcohol",
        label: "Do you drink alcohol?",
        type: "radio",
        options: [
          "Never",
          "Rarely (1–2 drinks/month)",
          "Socially (a few drinks/week)",
          "Regularly (most days)",
        ],
      },
      {
        id: "alcoholUnits",
        label: "If yes — roughly how many drinks per week?",
        type: "text",
        placeholder: "e.g. 4 beers on weekends",
        optional: true,
      },
    ],
  },
  {
    id: 3,
    key: "food",
    title: "Food",
    fullTitle: "Food Preferences",
    icon: "Utensils",
    color: "#f59e0b",
    questions: [
      {
        id: "favMeals",
        label: "Your top 5 favourite meals or dishes",
        type: "textarea",
        placeholder: "1. Chicken biryani\n2. Masala omelette\n3. Dal tadka\n4. Pizza\n5. Sushi",
      },
      {
        id: "hatedFoods",
        label: "Foods you absolutely hate and would never eat",
        type: "textarea",
        placeholder: "e.g. Bitter gourd, liver, sprouts...",
      },
      {
        id: "restrictions",
        label: "Dietary restrictions or allergies",
        type: "checkbox",
        options: [
          "None",
          "Vegetarian",
          "Vegan",
          "Dairy-free",
          "Gluten intolerant",
          "Nut allergy",
          "Egg-free",
          "Halal",
          "Other",
        ],
      },
      {
        id: "restrictOther",
        label: "If 'Other', describe",
        type: "text",
        placeholder: "e.g. low FODMAP, shellfish allergy...",
        optional: true,
      },
      {
        id: "cookStyle",
        label: "How do you prefer to cook / eat?",
        type: "radio",
        options: [
          "Cook from scratch daily",
          "Quick & simple (under 20 mins)",
          "Batch cook on weekends",
          "Mostly takeaway / eating out",
          "Mix of everything",
        ],
      },
      {
        id: "adventure",
        label: "Food adventurousness (1 = plain & safe → 10 = eat anything!)",
        type: "radio",
        options: ["1–2", "3–4", "5–6", "7–8", "9–10"],
      },
    ],
  },
  {
    id: 4,
    key: "snacks",
    title: "Snacks",
    fullTitle: "Snack Habits",
    icon: "Cookie",
    color: "#ef4444",
    questions: [
      {
        id: "currentSnacks",
        label: "What snacks do you currently reach for?",
        type: "textarea",
        placeholder: "e.g. Biscuits, chips, fruit, protein bars, nothing really...",
      },
      {
        id: "whySnack",
        label: "Why do you usually snack?",
        type: "checkbox",
        options: ["Genuine hunger", "Boredom", "Habit / automatic", "Stress or emotions", "I rarely snack"],
      },
      {
        id: "snackFlavour",
        label: "What do you prefer when snacking?",
        type: "radio",
        options: ["Mostly sweet", "Mostly savoury", "Sweet & spicy", "Both equally"],
      },
      {
        id: "lateNight",
        label: "Do you snack late at night (after 9 pm)?",
        type: "radio",
        options: ["Never", "Occasionally", "Most nights", "Every night — it's a habit"],
      },
      {
        id: "extra",
        label: "Anything else your nutritionist should know?",
        type: "textarea",
        placeholder: "e.g. I travel a lot, very busy at lunch, drink 3 coffees a day...",
        optional: true,
      },
    ],
  },
];
